CDI/CDI/Models/AspNetUsers.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetUsers
    {
        public string Id { get; set; }
        public string Email { get; set; }
        public bool EmailConfirmed { get; set; }
        public string PasswordHash { get; set; }
        public string SecurityStamp { get; set; }
        public string PhoneNumber { get; set; }
        public bool PhoneNumberConfirmed { get; set; }
        public bool TwoFactorEnabled { get; set; }
        public Nullable<System.DateTime> LockoutEndDateUtc { get; set; }
        public bool LockoutEnabled { get; set; }
        public int AccessFailedCount { get; set; }
        public string UserName { get; set; }
    }
}

CDI/CDI/Controllers/AspNetUserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CDI.Models;
using CDI.Models.ViewModels;
using System.Threading.Tasks;
using SweetAlert;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using Microsoft.AspNet.Identity.Owin;

namespace CDI.Controllers
{
    public class AspNetUserController : Controller
    {
        private ApplicationSignInManager _signInManager;
        private ApplicationUserManager _userManager;
        ApplicationDbContext context;
        public AspNetUserController()
        {
            context = new ApplicationDbContext();
        }

        public AspNetUserController(ApplicationUserManager userManager, ApplicationSignInManager signInManager)
        {
            UserManager = userManager;
            SignInManager = signInManager;
        }

        public ApplicationSignInManager SignInManager
        {
            get
            {
                return _signInManager ?? HttpContext.GetOwinContext().Get<ApplicationSignInManager>();
            }
            private set
            {
                _signInManager = value;
            }
        }

        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        public Boolean isAdminUser()
        {
            if (User.Identity.IsAuthenticated)
            {
                var user = User.Identity;
                var UserManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(context));
                var s = UserManager.GetRoles(user.GetUserId());
                if (s[0].ToString() == "Admin")
                {
                    return true;
                }
                else
                {
                    return false;
                }
            }
            return false;
        }




        // GET: AspNetUser
        public ActionResult Users()
        {


            if (User.Identity.IsAuthenticated)
            {


                if (!isAdminUser())
                {
                    return RedirectToAction("Index", "Home");
                }
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }





            List<ListUsersViewModel> lst;

            using (EntitiesCDI db = new EntitiesCDI())
            {
                lst = (from d in db.AspNetUsers
                           select new ListUsersViewModel
                           {
                               Id = d.Id,
                               UserName = d.UserName,
                               Email = d.Email
                           }).ToList();
            }
            return View(lst);
        }

        public ActionResult Editar(string Id)
        {
            ListUsersViewModel model = new ListUsersViewModel();
            using (EntitiesCDI db = new EntitiesCDI())
            {
                var oUser = db.AspNetUsers.Find(Id);
                model.UserName = oUser.UserName;
                model.Email = oUser.Email;
                model.Id = oUser.Id;
            }
            return View(model);
        }

        [HttpPost]
        public ActionResult Editar(ListUsersViewModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    using (EntitiesCDI db = new EntitiesCDI())
                    {
                        var oUser = db.AspNetUsers.Find(model.Id);
                        oUser.Id = model.Id;
                        oUser.UserName = model.UserName;
                        oUser.Email = model.Email;

                        db.Entry(oUser).State = System.Data.Entity.EntityState.Modified;
                        db.SaveChanges();
                    }
                    
                    return Redirect("/AspNetUser/Users");
                }

                return View(model);
            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message);
            }
        }

        [HttpGet]
        public ActionResult Eliminar(string Id)
        {
            using(EntitiesCDI db = new EntitiesCDI())
            {
                var oUser = db.AspNetUsers.Find(Id);
                db.AspNetUsers.Remove(oUser);
                db.SaveChanges();
            }
            return Redirect("/AspNetUser/Users");
        }


        //// POST: /Manage/ChangePassword
        //[HttpPost]
        //public async Task<ActionResult> Edit(ListUsersViewModel model)
        //{
        //    if (!ModelState.IsValid)
        //    {
        //        return View(model);
        //    }
        //    var result = await UserManager.ChangePasswordAsync(User.Identity.GetUserId(), model.OldPassword, model.NewPassword);
        //    if (result.Succeeded)
        //    {
        //        var user = await UserManager.FindByIdAsync(User.Identity.GetUserId());
        //        if (user != null)
        //        {
        //            await SignInManager.SignInAsync(user, isPersistent: false, rememberBrowser: false);
        //        }
        //        return RedirectToAction("Index", new { Message = ManageMessageId.ChangePasswordSuccess });
        //    }
        //    AddErrors(result);
        //    return View(model);
        //}





    }
}

CDI/CDI/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Security.Claims;
using System.Web.Security;
using Microsoft.AspNet.Identity;
using CDI.Models;
using Microsoft.AspNet.Identity.EntityFramework;

namespace CDI.Controllers
{
	[Authorize]
	public class UsersController : Controller
    {
		// GET: Users
		public Boolean isAdminUser()
		{
			if (User.Identity.IsAuthenticated)
			{
				var user = User.Identity;
				ApplicationDbContext context = new ApplicationDbContext();
				var UserManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(context));
				var s = UserManager.GetRoles(user.GetUserId());
				if (s[0].ToString() == "Admin")
				{
					return true;
				}
				else
				{
					return false;
				}
			}
			return false;
		}
		public ActionResult Index()
		{
			if (User.Identity.IsAuthenticated)
			{
				var user = User.Identity;
				ViewBag.Name = user.Name;
				//	ApplicationDbContext context = new ApplicationDbContext();
				//	var UserManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(context));

				//var s=	UserManager.GetRoles(user.GetUserId());
				ViewBag.displayMenu = "No";

				if (isAdminUser())
				{
					ViewBag.displayMenu = "Yes";
				}
				return View();
			}
			else
			{
				ViewBag.Name = "Not Logged IN";
			}


			return View();


		}
	}
}

CDI/CDI/Views/AspNetUser/Editar.cshtml
@model CDI.Models.ViewModels.ListUsersViewModel
@{
    ViewBag.Title = "Editar";
}

<h2>Editar</h2>

@using (Html.BeginForm("Editar", "AspNetUser", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()
    <h4>Editar cuenta.</h4>
    <hr />
    @Html.ValidationSummary("", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(m => m.UserName, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.UserName, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.UserName, "", new { @class = "text-danger" })
        </div>
    </div>    
    <div class="form-group">
        @Html.LabelFor(m => m.Email, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Email, new { @class = "form-control" })
        </div>
    </div>


    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" class="btn btn-default" value="Actualizar" />
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CDI/CDI/Views/AspNetUser/Users.cshtml
@model List<CDI.Models.ViewModels.ListUsersViewModel>
@{
    ViewBag.Title = "Usuarios";
}

<h2>ViewBag.Title</h2>


<script type="text/javascript">
        function DeleteConfirm() {
            if (confirm("Está seguro de eliminar el Registro"))
                return true;
            else
                return false;
        }
</script>


<div class="row" style="text-align:right;padding:5px">
    <a href="~/Account/Register" class="btn btn-primary">Registrar</a>
</div>
<div class="row">
    <div class="col-md-12">
        <table class="table">
            <tr>
                <th>#</th>
                <th>Usuario</th>
                <th>Email</th>
            </tr>
            @foreach (var oElemento in Model)
            {
                <tr>
                    <td>@oElemento.Id</td>
                    <td>@oElemento.UserName</td>
                    <td>@oElemento.Email</td>
                    <td>
                        <a class="btn btn-default" href="~/AspNetUser/Editar/@oElemento.Id">Editar</a>
                        <a onclick="return  DeleteConfirm()" class="btn btn-danger" href="~/AspNetUser/Eliminar/@oElemento.Id">Eliminar</a>
                    </td>
                </tr>
            }
        </table>
    </div>
</div>