CDI/CDI/Controllers/MaestroController.cs
using CDI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;
using CDI.Models.ViewModels;
using CDI.ViewModels;

namespace CDI.Controllers
{
    public class MaestroController : Controller
    {
        ApplicationDbContext context;

        public MaestroController()
        {
            context = new ApplicationDbContext();
        }

        // GET: Maestro


        //[HttpPost]
        public ActionResult Index(int? objectkey, int pagina = 1)
        {
            var cantidadRegistrosPorPagina = 5; // parámetro
            using (var db = new EntitiesCDI())
            {
                Func<CajeroMaestro, bool> predicado = x => !objectkey.HasValue || objectkey.Value == x.C_ObjectKey;

                var cajeros = (from d in db.CAJEROM
                              select new CajeroMaestro
                              {
                                  C_IdCajero = d.C_IdCajero,
                                  C_NombreCajero = d.C_NombreCajero,
                                  C_ObjectKey = d.C_ObjectKey
                              })
                    .OrderBy(x => x.C_ObjectKey)
                    .Skip((pagina - 1) * cantidadRegistrosPorPagina)
                    .Take(cantidadRegistrosPorPagina).ToList();
                var totalDeRegistros = db.CAJEROM.Count();

                var mod = new ViewModels.IndexViewModel();
                mod.Cajeros = cajeros;
                mod.PaginaActual = pagina;
                mod.TotalDeRegistros = totalDeRegistros;
                mod.RegistrosPorPagina = cantidadRegistrosPorPagina;
                mod.ValoresQueryString = new RouteValueDictionary();
                mod.ValoresQueryString["objectkey"] = objectkey;

                return View(mod);
            }
        }




        ///---------------------------------------------------------------------------
        public ActionResult Create()
        {
            var Detalle = new ATMViewModel();
            return View(Detalle);
        }

        [HttpPost]
        public ActionResult Create(ATMViewModel model, int id)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    using (EntitiesCDI db = new EntitiesCDI())
                    {
                        var purchCount = db.ATM.OrderByDescending(u => u.A_Id).FirstOrDefault();

                        var oATM = new ATM();
                        oATM.A_Id = purchCount.A_Id+1;
                        oATM.A_ObjectKey = id;
                        oATM.A_EmailAut = model.A_EmailAut;
                        oATM.A_NombreContacto = model.A_NombreContacto;
                        oATM.A_TelfContacto = model.A_TelfContacto;
                        oATM.A_ObsrvContacto = model.A_ObsrvContacto;
                        oATM.A_Observaciones = model.A_Observaciones;
                        oATM.A_HASlmDispensador = model.A_HASlmDispensador;
                        oATM.A_HASlmOtrosModulos = model.A_HASlmOtrosModulos;
                        oATM.A_HAFlmTDV = model.A_HAFlmTDV;
                        oATM.A_HAFlmTOC = model.A_HAFlmTOC;
                        oATM.A_HSAtm = model.A_HSAtm;
                        oATM.A_HSOficina = model.A_HSOficina;
                        oATM.A_ATMUptimeU6 = model.A_ATMUptimeU6;
                        oATM.A_TransaccU6 = model.A_TransaccU6;

                        db.ATM.Add(oATM);
                        db.SaveChanges();
                    }

                    return Redirect("~/Maestro/Index");
                }

                return View(model);


            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message);
            }
        }
        ///---------------------------------------------------------------------------

        
        //[HttpPost]
        //public ActionResult Editar(ListUsersViewModel model)
        //{
        //    try
        //    {
        //        if (ModelState.IsValid)
        //        {
        //            using (EntitiesCDI db = new EntitiesCDI())
        //            {
        //                var oUser = db.AspNetUsers.Find(model.Id);
        //                oUser.Id = model.Id;
        //                oUser.UserName = model.UserName;
        //                oUser.Email = model.Email;

        //                db.Entry(oUser).State = System.Data.Entity.EntityState.Modified;
        //                db.SaveChanges();
        //            }

        //            return Redirect("/AspNetUser/Users");
        //        }

        //        return View(model);
        //    }
        //    catch (Exception ex)
        //    {
        //        throw new Exception(ex.Message);
        //    }
        //}



    }

}

CDI/CDI/Views/Maestro/Create.cshtml
@model CDI.ViewModels.ATMViewModel
@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm("Create", "Maestro", FormMethod.Post))
{
    <div class="row">
        <div class="col-md-12">
            <div>
                @Html.LabelFor(d => d.A_ObjectKey)
                @Html.TextBoxFor(d => d.A_ObjectKey, "", new { @class = "form-control" })
                @Html.ValidationMessageFor(d => d.A_ObjectKey, null, new { @class = "red" })
            </div>
            <div>
                @Html.LabelFor(d => d.A_EmailAut)
                @Html.TextBoxFor(d => d.A_EmailAut, "", new { @class = "form-control" })
                @Html.ValidationMessageFor(d => d.A_EmailAut, null, new { @class = "red" })
            </div>
            <div>
                @Html.LabelFor(d => d.A_NombreContacto)
                @Html.TextBoxFor(d => d.A_NombreContacto, "", new { @class = "form-control" })
                @Html.ValidationMessageFor(d => d.A_NombreContacto, null, new { @class = "red" })
            </div>
            <div>
                @Html.LabelFor(d => d.A_TelfContacto)
                @Html.TextBoxFor(d => d.A_TelfContacto, "", new { @class = "form-control" })
                @Html.ValidationMessageFor(d => d.A_TelfContacto, null, new { @class = "red" })
            </div>
            <div>
                @Html.LabelFor(d => d.A_ObsrvContacto)
                @Html.TextBoxFor(d => d.A_ObsrvContacto, "", new { @class = "form-control" })
                @Html.ValidationMessageFor(d => d.A_ObsrvContacto, null, new { @class = "red" })
            </div>
            <div>
                @Html.LabelFor(d => d.A_Observaciones)
                @Html.TextBoxFor(d => d.A_Observaciones, "", new { @class = "form-control" })
                @Html.ValidationMessageFor(d => d.A_Observaciones, null, new { @class = "red" })
            </div>
            <br />
            <div style="text-align:right;">
                <input value="Guardar" class="btn btn-primary" type="submit" />
            </div>
        </div>

    </div>
}

CDI/CDI/Views/Maestro/Index.cshtml
@model CDI.ViewModels.IndexViewModel
@{
    ViewBag.Title = "Maestro Detalle";
}

<h2>@ViewBag.Title</h2>

<h4>Filtrar</h4>
@using (Html.BeginForm(null, null, FormMethod.Get))
{
    <label for="objectkey">Código Cajero</label>
    <input type="number" name="objectkey" id="objectkey" />
    <input type="submit" value="Filtrar" class="btn btn-success" />
}

<div class="row">
    <div class="col-md-12">
        <table id="example" class="table table-striped table-bordered table-sm" cellspacing="0" width="100%">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Código Cajero</th>
                    <th>ObjectKey</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var oElemento in Model.Cajeros)
                {
                    <tr>
                        <td>@oElemento.C_IdCajero</td>
                        <td>@oElemento.C_NombreCajero</td>
                        <td>@oElemento.C_ObjectKey</td>
                        <td>
                            <a class="btn btn-default" href="~/Maestro/Create/@oElemento.C_ObjectKey">Editar</a>
                            @*<a onclick="return  DeleteConfirm()" class="btn btn-danger" href="~/AspNetUser/Eliminar/@oElemento.Id">Eliminar</a>*@
                        </td>
                    </tr>
                }
            </tbody>
            <tfoot>
                <tr>
                    <th>
                        #
                    </th>
                    <th>
                        Código Cajero
                    </th>
                    <th>
                        ObjectKey
                    </th>
                    
                </tr>
            </tfoot>
        </table>
        @{Html.RenderPartial("_paginador", Model);}
    </div>
</div>



@using (Html.BeginForm("Create", "Maestro", FormMethod.Post))
{
    <div class="details">
        <h2>
            Detalle Cajeros
        </h2>
        <table class="table table-responsive">
            <tr>
                @*<td>A_ObjectKey</td>*@
                <td>A_EmailAut</td>
                <td>A_NombreContacto</td>
                <td>A_TelfContacto</td>
                <td>A_ObsrvContacto</td>
                <td>A_Observaciones</td>
                <td>A_HASlmDispensador</td>
                <td>A_HASlmOtrosModulos</td>
                <td>A_HAFlmTDV</td>
                <td>A_HAFlmTOC</td>
                <td>A_HSAtm</td>
                <td>A_HSOficina</td>
                <td>A_ATMUptimeU6</td>
                <td>A_TransaccU6</td>
                <td>&nbsp;</td>
            </tr>
            <tr class="mycontainer" id="mainrow">
                <td>
                    @*<input type="text" id="A_ObjectKey" class="A_ObjectKey form-control" />*@
                    @*<label class="sr-only" for="A_ObjectKey">A_ObjectKey</label>
                    <input type="text" class="form-control" id="A_ObjectKey" placeholder="ObjectKey">*@
                    @*@Html.TextBoxFor(m => m.A_ObjectKey, new { @class = "form-control" })*@
                    @Html.HiddenFor(a => a.A_ObjectKey)
                </td>
                <td>
                    
                    @Html.TextBoxFor(m => m.A_EmailAut, new { @class = "form-control" })
                    @*<input type="text" id="A_EmailAut" class="A_Email form-control" />*@
                </td>
                <td>
                    @Html.TextBoxFor(m => m.A_NombreContacto, new { @class = "form-control" })
                    @*<input type="text" id="A_NombreContacto" class="A_NombreContacto form-control" />*@
                </td>
                <td>
                    @Html.TextBoxFor(m => m.A_TelfContacto, new { @class = "form-control" })
                    @*<input type="text" id="A_TelfContacto" class="A_TelfContacto form-control" />*@
                </td>

                <td>
                    @Html.TextBoxFor(m => m.A_ObsrvContacto, new { @class = "form-control" })
                    @*<input type="text" id="A_ObsrvContacto" class="A_ObsrvContacto form-control" />*@
                </td>
                <td>
                    @Html.TextBoxFor(m => m.A_Observaciones, new { @class = "form-control" })
                    @*<input type="text" id="A_Observaciones" class="A_Observaciones form-control" />*@
                </td>
                <td>
                    @Html.TextBoxFor(m => m.A_HASlmDispensador, new { @class = "form-control" })
                    @*<input type="text" id="A_HASlmDispensador" class="A_HASlmDispensador form-control" />*@
                </td>
                <td>
                    @Html.TextBoxFor(m => m.A_HASlmOtrosModulos, new { @class = "form-control" })
                    @*<input type="text" id="A_HASlmOtrosModulos" class="A_HASlmOtrosModulos form-control" />*@
                </td>

                <td>
                    @Html.TextBoxFor(m => m.A_HAFlmTDV, new { @class = "form-control" })
                    @*<input type="text" id="A_HAFlmTDV" class="A_HAFlmTDV form-control" />*@
                </td>
                <td>
                    @Html.TextBoxFor(m => m.A_HAFlmTOC, new { @class = "form-control" })
                    @*<input type="text" id="A_HAFlmTOC" class="A_HAFlmTOC form-control" />*@
                </td>
                <td>
                    @Html.TextBoxFor(m => m.A_HSAtm, new { @class = "form-control" })
                    @*<input type="text" id="A_HSAtm" class="A_HSAtm form-control" />*@
                </td>
                <td>
                    @Html.TextBoxFor(m => m.A_HSOficina, new { @class = "form-control" })
                    @*<input type="text" id="A_HSOficina" class="A_HSOficina form-control" />*@
                </td>

                <td>
                    @Html.TextBoxFor(m => m.A_ATMUptimeU6, new { @class = "form-control" })
                    @*<input type="text" id="A_ATMUptimeU6" class="A_ATMUptimeU6 form-control" />*@
                </td>
                <td>
                    @Html.TextBoxFor(m => m.A_TransaccU6, new { @class = "form-control" })
                    @*<input type="text" id="A_TransaccU6" class="A_TransaccU6 form-control" />*@
                </td>
                <td>
                    <input type="button" id="add" value="Añadir" style="width:80px" class="btn btn-success" />
                </td>
            </tr>
        </table>
        @*<div id="orderItems">
            <table class="table table-responsive" id="orderdetailsItems"></table>
            <span id="orderItemError" style="color:red"></span>
        </div>
        <div style="padding:10px 0; text-align:right">
            <input id="submit" type="button" value="Guardar Orden" class="btn btn-warning" style="padding:10px 20px" />
        </div>*@

        <div class="form-group">
            <input type="submit" />
        </div>
    </div>
}

<link href="~/Content/bootstrap.min.css" rel="stylesheet" />
<link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css" />
<script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
<script src="~/Scripts/myScripts.js"></script>
<script type="text/javascript">
    $(function () {
        $('#orderDate').datepicker({
            dateFormat: 'mm-dd-yy'
        })
    })
</script>
<style>
    span.error {
        display: block;
        visibility: hidden;
        color: red;
        font-size: 90%;
    }

    tr.error {
        background-color: rgba(255,0,0,0.35);
    }
</style>




    @*/*<script > var num = 0; function AgregaConcepto() {
        let Cantidad = document.getElementById("Cantidad").value;
        let Precio = document.getElementById("Precio").value;
        let Nombre = document.getElementById("Nombre").value;
        //agregamos tabla let Tabla = document.getElementById("tablaConceptos");
        let TR = document.createElement("tr");
        let TDCantidad = document.createElement("td");
        let TDNombre = document.createElement("td");
        let TDPrecio = document.createElement("td");
        let TDTotal = document.createElement("td");
        TR .appendChild(TDCantidad);
        TR .appendChild(TDNombre);
        TR .appendChild(TDPrecio);
        TR .appendChild(TDTotal);
        TDCantidad .innerHTML = Cantidad;
        TDNombre .innerHTML = Nombre;
        TDPrecio .innerHTML = Precio;
        TDTotal .innerHTML = parseFloat(Cantidad) * parseFloat(Precio);
        Tabla .appendChild(TR);
        //agregamos hiddens let DivConceptos = document.getElementById("divConceptos");
        let HiddenIndex = document.createElement("input");
        let HiddenCantidad = document.createElement("input");
        let HiddenNombre = document.createElement("input");
        let HiddenPrecio = document.createElement("input");
        HiddenIndex .name = "conceptos.Index";
        HiddenIndex .value = num;
        HiddenIndex .type = "hidden";
        HiddenCantidad .name = "conceptos[" + num + "].Cantidad";
        HiddenCantidad .value = Cantidad;
        HiddenCantidad .type = "hidden";
        HiddenNombre .name = "conceptos[" + num + "].Nombre";
        HiddenNombre .value = Nombre;
        HiddenNombre .type = "hidden";
        HiddenPrecio .name = "conceptos[" + num + "].PrecioUnitario";
        HiddenPrecio .value = Precio;
        HiddenPrecio .type = "hidden";
        DivConceptos .appendChild(HiddenIndex);
        DivConceptos .appendChild(HiddenCantidad);
        DivConceptos .appendChild(HiddenNombre);
        DivConceptos .appendChild(HiddenPrecio);
        document .getElementById("Cantidad").value = "";
        document .getElementById("Precio").value = "";
        document .getElementById("Nombre").value = "";
        num ++;
    }

    </script >*/*@